<?xml version="1.0" encoding="UTF-8"?> 
<!DOCTYPE stock [
    <!ELEMENT stock (new-car*,used-car*)>
    <!ELEMENT new-car (model?,price?)>
    <!ELEMENT used-car (model?,mileage?,price?,condition?)>
    <!ELEMENT model (#PCDATA)>
    <!ELEMENT price (#PCDATA)>
    <!ELEMENT mileage (#PCDATA)>
    <!ELEMENT condition (#PCDATA)>
]>
<stock>
    <new-car>
        <model>Ferrari SF23</model>
        <price>20000000</price>
    </new-car>
    <new-car>
        <model>Renault Megane RS</model>
        <price>42999</price>
    </new-car>
    <used-car>
        <model>Seat Leon</model>
        <mileage>437000</mileage>
        <price>5000</price>
        <condition>Beaten up</condition>
    </used-car>
    <used-car>
        <model>Alfa Romeo Giulia Quadrifoglio</model>
        <mileage>65000</mileage>
        <price>33000</price>
        <condition>Unscratched</condition>
    </used-car>
    <used-car>
        <model>Alpine A110</model>
        <mileage>2000</mileage>
        <price>3000</price>
        <condition>Caught fire, engine exploded</condition>
    </used-car>
</stock>