=== Xabi-5/LinguaxesXSD/DTD/validation/address.dtd
<!ELEMENT address (name,company,phone,city*,(personal|work|vacation))>
<!ELEMENT name (#PCDATA)>
<!ATTLIST name number CDATA #REQUIRED>
<!ELEMENT company (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ATTLIST phone prefix CDATA #REQUIRED>
<!ELEMENT city ANY>
<!ATTLIST city state CDATA #FIXED "EspaÃ±a">
<!ELEMENT cityName (#PCDATA)>
<!ELEMENT zipCode (#PCDATA)>
<!ELEMENT personal EMPTY>
<!ELEMENT work EMPTY>
<!ELEMENT vacation EMPTY>

=== Xabi-5/LinguaxesXSD/DTD/validation/address.xml
<?xml version="1.0" encoding="UTF-8"?> 
<!DOCTYPE address SYSTEM "address.dtd">
<address>
    <name number="12">Enrico Pane</name>
    <company>Fenosa</company>
    <phone prefix="(011)">634382828</phone>
    <city>
        <cityName>Boiro</cityName>
        <zipCode>15930</zipCode>
    </city>
    <personal />
    
</address>
