=== Xabi-5/LinguaxesXSD/XSD/ex23/university.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="university">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="school" type="StaffType">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string" />
                            <xs:element name="location" type="xs:string" />
                            <xs:element name="schoolStaff">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="staff" type="StaffType">
                                            
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="subjects">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="subject">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="name" type="xs:string" />
                                                    <xs:element name="description" type="xs:string" />
                                                    <xs:element name="capacity" type="xs:string" />
                                                    <xs:element name="lecturers">
                                                        <xs:complexType>
                                                            <xs:attribute name="lecCode"
                                                                type="xs:IDREF" use="required" />
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                                <xs:attribute name="code" type="xs:IDREF"
                                                    use="required" >
                                                    </xs:attribute>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="idSchool" type="xs:ID" use="required" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="categories">
        <xs:list>
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="academic"/>
                    <xs:enumeration value="general"/>
                    <xs:enumeration value="technical"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:list>
    </xs:simpleType>
    <xs:complexType name="StaffType">
            <xs:sequence>
                <xs:element name="staff">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="category" type="categories" />
                            <xs:element name="address" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="street"
                                            type="xs:string" />
                                        <xs:element name="suburb"
                                            type="xs:string" />
                                        <xs:element name="postcode"
                                            type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="idStaff" type="xs:ID"
                            use="required" />
                        <xs:attribute name="name" use="required" />
                        <xs:attribute name="title" use="required" />
                        <xs:attribute name="category" use="required" />
    </xs:complexType>
</xs:schema>

=== Xabi-5/LinguaxesXSD/XSD/ex23/university.xml
<?xml version="1.0" encoding="UTF-8"?>
<university xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="university.xsd">
    <school idSchool='I1S'>
        <name>International School of Language</name>
        <location>Rue de la Grenouille 17</location>
        <schoolStaff>
            <staff idStaff='S1' name='Pierre Leclerc' title='PhD in Italian literature' category='academic'>
                <address>
                    <street>Rue de Sbinnala</street>
                    <suburb>Montecarlo</suburb>
                    <postcode>20750</postcode>
                </address>
                <address>
                    <street>Via Musso</street>
                    <suburb>Maranello</suburb>
                    <postcode>70708</postcode>
                </address>
            </staff>
        </schoolStaff>
        <subjects>
            <subject code='C3'>
                <name>French 1</name>
                <description>First year of the french language</description>
                <capacity>60</capacity>
                <lecturers lecCode='S1'/>
            </subject>
        </subjects>
    </school>
</university>
