=== Xabi-5/LinguaxesXSD/XSD/ex21/company.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="company">
        <xs:complexType>
            <xs:all>
                <xs:element name="general_information" type="GeneralInfoType">
                </xs:element>
                <xs:element name="staffInformation">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="department" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="employee" type="EmployeeType" minOccurs="0" maxOccurs="3"/>
                                    </xs:sequence>
                                    <xs:attributeGroup ref="departmentAG"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="date" type="xs:date" use="required" />
                    </xs:complexType>
                </xs:element>
            </xs:all>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="sector">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Technology"/>
            <xs:enumeration value="Education"/>
            <xs:enumeration value="Finances"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="GeneralInfoType">
        <xs:sequence>
            <xs:element name="name" type="textType" />
            <xs:element name="numEmployees" type="xs:integer" />
            <xs:element name="sector" type="sector" />
        </xs:sequence>
        <xs:attribute name="multinational" type="xs:boolean" use="required" />
        <xs:attribute name="currency" type="xs:string" fixed="euro"/>
    </xs:complexType>
    <xs:simpleType name="salary">
        <xs:restriction base="xs:decimal">
            <xs:minExclusive value="1000"/>
            <xs:maxExclusive value="9999"/>
            <xs:fractionDigits value="2"/>
            <xs:totalDigits value="6"/> 
        </xs:restriction>
    </xs:simpleType>

    <xs:attributeGroup name="departmentAG">
        <xs:attribute name="code" use="required"  />
        <xs:attribute name="name" use="required" />
    </xs:attributeGroup>

    <xs:complexType name="EmployeeType">
        <xs:sequence>
            <xs:element name="name" type="textType" />
            <xs:element name="role" type="xs:string" />
            <xs:element name="sickLeave">
                <xs:complexType>
                    <xs:attribute name="has" use="required" />
                </xs:complexType>
            </xs:element>
            <xs:element name="salary" type="xs:float" />
            <xs:element name="user">
                <xs:complexType>
                    <xs:attribute name="name" use="required" />
                </xs:complexType>
            </xs:element>
            <xs:element name="key" type="xs:string" />
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="textType">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
            <xs:maxLength value="40"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== Xabi-5/LinguaxesXSD/XSD/ex21/company.xml
<?xml version="1.0" encoding="UTF-8"?>
<company xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="company.xsd">
    <general_information multinational = "false" currency = "euro">
        <name> XML Technologies </name>
        <numEmployees> 6 </numEmployees>
        <sector>Technology</sector>
    </general_information>

    <staffInformation date="2023-03-02">
        <department code ="ADMIN" name="Administracion">
            <employee>
                <name>Alicia Torres Pan</name>
                <role>Head of Department</role>
                <sickLeave has="NO"></sickLeave>
                <salary>2250.00</salary>
                <user name="atorres"></user>
                <key>3%abYki6</key>
            </employee>
            <employee>
                <name>Xoán Aldrei Soto</name>
                <role>Employee</role>
                <sickLeave has="YES"></sickLeave>
                <salary>1200.00</salary>
                <user name="xaldrei"></user>
                <key>6@hjKm87</key>
            </employee>
            <employee>
                <name>Ana Mota Rei</name>
                <role>Employee</role>
                <sickLeave has="NO"></sickLeave>
                <salary>1250.50</salary>
                <user name="amotar"></user>
                <key>4%wtrtHQ</key>
                </employee>
        </department>
       
       <department code="COMPU" name="Administracion">
            <employee>
                <name>Óscar Baltar Dacosta</name>
                <role>Head of Department</role>
                <sickLeave has="YES"></sickLeave>
                <salary>2300.75</salary>
                <user name="obaltar"></user>
                <key>8$abcdHj</key>
            </employee>
            <employee>
                <name>Helena Vilar Moure</name>
                <role>Employee</role>
                <sickLeave has="NO"></sickLeave>
                <salary>1500.35</salary>
                <user name="hvilar"></user>
                <key>9?sdKp:s</key>  
            </employee>
            <employee>
                <name>Andrea Seroido Paz</name>
                <role>Head of Department</role>
                <sickLeave has="NO"></sickLeave>
                <salary>2500.85</salary>
                <user name="guest"></user>
                <key>9?sdKp:s</key>  
            </employee>
            
       </department>
       
    </staffInformation>
</company>
